GDSCITM/GDSCITM-official-website

.github/ISSUE_TEMPLATE/bug.yaml

🚀 Feature add: Added issue template

---

.npmrc
package-lock.json
src/Pages/Home.js

Close: #6 
I Fixed the home input email hidden part when the user has to type a long email address.
1: ```Home.js```

Fix: Email gets hide when user types their email

---

.github/ISSUE_TEMPLATE/feature.yaml

Created feature.yaml file for feature issue template

Added template feature issue template 

---

.github/ISSUE_TEMPLATE/documentation.yaml

added documentation.yaml for documentation related issue

added documentation.yaml for documentation related issue

---

README.md

closes #25 
- Broken link is replaced by new link.

Readme broken Link Fixed

---

src/Components/SliderComponent.js

fix: padding fixed

---

README.md

docs: Modified README file by adding maintainers section

---

Contributors.md

docs: Added Contributors.md

---

src/Pages/Event/Event.css
src/Pages/Event/Event.js

I've added the following to fix the existing issues of events tab:
* on click on particular tab, data is shown of that section only. If we click on active tab, data doesn't change.
* 'Past' tab functionality added
* Tab button cursor is set to pointer

fix: #39 Events tab

---

README.md

Fix contributors count

---

src/Pages/Home.css
src/Pages/Home.js

Hi, I have updated input, button and surrounding text as per Figma design. please have a look into it.

input responsiveness updated

---

README.md

Added discord link

---

README.md

Updated License bar to display MIT and Link to Project License 

---

src/Components/Header.js

Header text font size in small screen fixed

---

.github/pull_request_template.md

This pr is for the pull request template been added #49

pull request template added

---

src/Components/AboutSection.js

This PR fixes #82
I have just changed the css in which I have changed the padding only .

spacing successfully done

---

.github/pull_request_template.md
public/index.html
src/App.js
src/Components/AboutSection.js
src/Components/Header.js
src/Components/SliderComponent.js
src/theme.js

Fixed merge conflict

---

src/App.css
src/Pages/Home.js

This PR fixes #90 
- Alignment issue for small screens
- made css changes to fix the responsive alignment in the home screen

fix: responsive alignment fixed

---

src/Components/SliderComponent.js
src/Pages/Event/Event.js
src/Pages/Home.js
src/Pages/Teams.js

This PR fixes #111 input field now works
changed the position of input and button next to it needed some margin left so that input and button both works

its fixed input works now

---

src/App.js
src/Pages/Event/Event.css
src/Pages/Event/Event.js
src/Pages/Event/MobileUpcoming.js
src/Pages/Event/Upcoming.js

This PR fixes #38
I wanted to give you an update on the design of our cards. I know I initially tried to create responsive cards using the design in Figma, but I ran into some issues along the way. So, I had to create a new file and start from scratch with a separate design for the cards.
I did my best to make the cards as similar to the original design as possible, but I want to make sure you're happy with the end result. If there's anything you want me to change, just let me know! I always appreciate your feedback and want to make sure I'm meeting your expectations.
Thanks for your patience and support while I work through these challenges.
BEFORE:
AFTER:

Changed cards design for Event section

---

src/Components/AboutSection.js
src/Components/Header.js
src/Pages/Event/Event.js
src/Pages/Home.js
src/Pages/Teams.js
src/index.css

On ciick on each nav item, it redirects you to the specific section of the page
This PR fixes #91 
**Describe the changes you've made:**
Wrapped each of the nav-bar items in the Header component with a link component.

Added link tags to each nav-item on the navbar in the Header component

---

src/Components/SliderComponent.js
src/index.css

This PR fixes #
add github icon team slider cards
imported adn added icon to component

added github icon

---

src/Components/Alternative/Home/Home.js

This PR fixes #124 
I made changes to this path: src -> components -> alternative -> home -> home.js.
I changed journey to journey (typo) in the home.js file.

fixed typo

---

src/Components/Alternative/Header.js

This PR fixes #122 
* Scrolls to top on logo click

Scroll to top on logo click

---

src/Pages/Event/Event.css

Added top padding in the inner card content.

---

src/Components/Alternative/Header.js
src/Components/Alternative/Header.module.css

This PR fixes #107
Describe the changes you've made: 
- I made changes to Header.js and Header. module.css.

successfully redirect to give link

---

src/Components/Alternative/Header.js
src/Components/Alternative/Header.module.css

This PR fixes #125
- I made changes in Header.js and Header.module.css files
- added a span tag around the "join us" text and added little styling to it.

Hemanth paila join button font

---

src/Components/Alternative/Home/Home.module.css

This PR fixes #147 
Fixed hero section alignment in mobile view according to the desired design: https://www.figma.com/file/PZcP2X9CdePgwlQqy8Ym5Y/GDSC-(Copy)?node-id=0%3A1&t=du9dGcaWFeJu1BM6-1

fixed hero section alignment in mobile view

---

src/Components/Alternative/Header.js
src/Components/Alternative/Header.module.css
src/Pages/Event/Event.css

This PR fixes #
#12 
#104 
added hamburger menu with working and responsive
also, change in event css added margin in the data

added hamburger menu with working 

---

src/Components/Alternative/gallery/gallery.js

add gallery fetch images function

---

src/Components/SliderComponent.js
src/Components/slider.css

This pr fixes #155 
The team card size scales up and box shadow is getting darker on hover.

Feature: Add Hover effect on team card

---

src/Components/Alternative/Header.js

<#158>
This PR fixes #158 
Changed the inline style (height to 70px) in Components/Alternative/Header.js line 58
Thank you for contributing to GDSCITM! 
Contributing Conventions:
- Include descriptive PR titles with [Components/Alternative/Header.js] prepended.
By following the community's contribution conventions upfront, the review process will 
be accelerated and your PR merged more quickly.
-->

fixed issue #158 - Components/Alternative/Header.js

---

src/Pages/Footer/Footer.js

Fix Serif font in footer
Before:
After:

Fix Serif font in footer

---

src/App.js
src/Components/Alternative/contributors/Contributors.module.css
src/Components/Alternative/contributors/contributors.js

This PR fixes #
added new contributors section

added new contributors section

---

package-lock.json
package.json
src/Components/Alternative/about/about.js
src/Components/Alternative/contributors/Contributors.module.css
src/Components/Alternative/gallery/gallery.js
src/Components/SliderComponent.js
src/Components/slider.css
src/Pages/Event/Event.css
src/Pages/Footer/Footer.css
src/Pages/Footer/Footer.js

**Description**:
I've made several improvements in the design of the website:
1. Improved the overall design for a more visually appealing look.
2. Added a carousel in the gallery section to showcase images more interactively.
3. Changed the color of links in the footer section to match the theme (#D4D4D4).
4. Updated social icons to use React icons with the color #D4D4D4 to match the theme.
5. Fixed responsiveness in the events and teams sections:
- Ensured that cards in the events section adjust to the screen size.
- Improved the layout for better responsiveness in the teams section.
**Screenshots**:
| Before | After|
| ------ | ---- |
| ![Before](https://placeholder.pics/svg/300) | ![After](https://placeholder.pics/svg/300) |
**System**:
* Browser:
* Version:
* OS:
**Issue**:

Enhancements in design and functionality

---

src/Components/Alternative/Header.js
src/Components/Alternative/Header.module.css
src/Components/HeaderCss.js

**Description**: I have solve the issue of mobile navigation 
**Screenshots**:
After[
**System**:
* Browser: edge
* Version: 
* OS: windows 
**Issue**: mobile navigation problem

resolved some issue

---

public/index.html
src/index.css

**Description**: I have the solved the issue of whitespace in mobile view, in this code few mistake of index.css file.
**Screenshots**:
Before[
]
After[
]
**System**:
* Browser: Microsoft edge
* Version:
* OS: windows 11
**Issue**: whitespace issue in mobile view

solve whitespace issue
